name: Tests and push apps

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Check code linting
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint

  dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Check code typing
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: typecheck

      - name: Run unit tests
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test --coverage

  build:
    runs-on: ubuntu-latest
    needs: [style, dashboard]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: |
            glapss/dashboard:latest
            ghcr.io/vlidtara/dashboard2:latest
